### ISSUE TITLE
is it convenient for you to upload your test data?

### ISSUE THREAD

**Issue by tinymindxx** [nuankw/Summer-Research-2018-Part-One#5]
hi, thanks for your work. 
I have been looking for an implemtation of DeepAR for a long time, it's really nice of you to share you work, many thanks again. And I wonder whether you can upload your test data?

**Comment by nuankw** [comment]
Hi @frozenxia, thanks a lot for reaching out! It's good to know that someone's also working on this. We used the electricity dataset as mentioned in the paper, and I believe you will be able to find it somewhere on the internet.
Happy coding and all the best!
